services:
  onsite:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - "80:80"
      - "8000"
    stdin_open: true
    tty: true
    isolation: process
